from instr import *
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QApplication,QWidget,QLabel,QPushButton,QVBoxLayout,QHBoxLayout,QLineEdit)
from FinalWin import *
class TestWin(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()
        self.connects()
        self.set_appear()
        self.show()
    def set_appear(self):
        self.setWindowTitle(txt_title)
        self.resize(win_width,win_height)
        self.move(win_x,win_y)
    def initUI(self):
        self.but1=QPushButton(txt_b1)
        self.but2=QPushButton(txt_b2)
        self.but3=QPushButton(txt_b3)
        self.but4=QPushButton(txt_b4)
        self.textname=QLabel(txt_name)
        self.age=QLabel(txt_age)
        self.textinstur1=QLabel(txt_test1)
        self.textinstur2=QLabel(txt_test2)
        self.textinstur3=QLabel(txt_test3)
        self.timere=QLabel(txt_timer)
        self.surname=QLineEdit(txt_surname)
        self.test1=QLineEdit(txt_t01)
        self.test2=QLineEdit(txt_t02)
        self.test3=QLineEdit(txt_t03)
        self.test4=QLineEdit(txt_t04)
        self.lineh=QHBoxLayout()
        self.liner=QVBoxLayout()
        self.linel=QVBoxLayout()
        self.liner.addWidget(self.timere,alignment=Qt.AlignCenter)
        self.linel.addWidget(self.textname,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.surname,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.age,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.test1,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.textinstur1,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.but1,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.test2,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.textinstur2,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.but2,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.textinstur3,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.but3,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.test3,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.test4,alignment=Qt.AlignLeft)
        self.linel.addWidget(self.but4,alignment=Qt.AlignRight)
        self.lineh.addLayout(self.linel)
        self.lineh.addLayout(self.liner)
        self.setLayout(self.lineh)
    def next_click(self):
        self.hide()
        self.tw=FinalWin()
    def connects(self):
        self.but4.clicked.connect(self.next_click)
